export const appCopy = {
  ckb: {
    home: 'سەرەکی',
    community: 'کێشەی سەیارە',
    settings: 'ڕێکخستنەکان',
    favorites: 'دڵخوازەکان',
    greeting: 'هەر کوێیەک بیت، یارمەتی نزیکە',
    headline: 'ڕێگاکەت بەردەوامە.',
    intro:
      'فیتەری گونجاوت بدۆزەوە، کێشەکەت چارەسەر بکە و بە دڵنیاییەوە بگەڕێوە سەر ڕێگا.',
    network: 'تۆڕی خزمەتگوزاریی سلێمانی',
    help: 'پێویستت بە یارمەتییە؟',
    helpText:
      'شوێنەکەت دیاری بکە. داواکارییەکەت دەگاتە فیتەرێکی نزیک و بەردەست.',
    request: 'داوای فیتەر بکە',
    browse: 'فیتەرەکان بدۆزەوە',
    explore: 'لە نەخشەدا بگەڕێ',
    available: 'بەردەستە',
    offline: 'بەردەست نیە',
    busy: 'سەرقاڵە',
    saved: 'فیتەرە دڵخوازەکانت',
    savedText: 'فیتەرەکانی پاشەکەوتت کردوون، لە یەک شوێن.',
    save: 'زیادکردن بۆ دڵخوازەکان',
    unsave: 'لابردن لە دڵخوازەکان',
    savedEmpty: 'هێشتا فیتەرێکت پاشەکەوت نەکردووە',
    savedHint: 'دڵەکەی سەر کارتی فیتەرێک هەڵبژێرە بۆ ئەوەی لێرە بیبینیتەوە.',
    allFitters: 'هەموو فیتەرەکان',
    filters: 'پاڵاوتن',
    byDistance: 'نزیکترین',
    byRating: 'بەرزترین هەڵسەنگاندن',
    area: 'هەموو ناوچەکان',
    list: 'فیتەر',
    noRating: 'هێشتا هەڵسەنگاندنی نییە',
    serviceNote: 'خزمەتگوزاری بەپێی پێویستی تۆ',
    mapTitle: 'یارمەتی لە نزیکت',
    mapText: 'دووکان و فیتەری گەڕۆک لەسەر نەخشە بدۆزەوە.',
    how: 'چۆن کار دەکات؟',
    steps: [
      'شوێنەکەت دیاری بکە',
      'فیتەر داواکارییەکەت قبوڵ دەکات',
      'کارەکە تەواو دەبێت؛ هەڵیسەنگێنە',
    ],
    communityTitle: 'کێشەکەت لەگەڵ فیتەرەکان باس بکە',
    communityText:
      'دەنگێکی نامۆ؟ کێشەی تایە؟ وردەکاری بنووسە و وەڵامی فیتەرەکان ببینە.',
    communityAction: 'چوونە ناو گفتوگۆکان',
    private: 'ژمارەی فیتەرەکان پارێزراوە؛ داواکاری لە ناو ئەپەکە بەڕێوە دەچێت.',
    appearance: 'ڕووکار',
    preferences: 'بە دڵی خۆت ڕێکی بخە',
    settingsIntro: 'زمان، ڕووکار و زانیارییەکانت لە یەک شوێن.',
    dark: 'تاریک',
    light: 'ڕووناک',
    system: 'بەپێی ئامێر',
    city: 'شار',
    cityHint: 'ئێستا خزمەتگوزاری لە سلێمانی بەردەستە.',
    location: 'پیشاندانی دووری لە تۆ',
    locationHint:
      'شوێن تەنها بە ڕەزامەندی تۆ وەردەگیرێت. لە ئامێرەکەتدا پاشەکەوت ناکرێت.',
    enabled: 'چالاکە',
    disabled: 'ناچالاکە',
    share: 'هاوبەشکردنی ئەپەکە',
    copied: 'بەستەر کۆپی کرا',
    install: 'دامەزراندنی ئەپ',
    installHint: 'لە مێنیوی وێبگەڕ، «زیادکردن بۆ شاشەی سەرەکی» هەڵبژێرە.',
    privacy: 'تایبەتمەندی',
    terms: 'مەرجەکانی بەکارهێنان',
    about: 'دەربارەی نزیکترین فیتەر',
    localSaved: 'دڵخوازەکان لەم ئامێرە پاشەکەوت دەکرێن.',
    version: 'وەشانی ٢.٠ · بە خۆشەویستی بۆ ڕێگاکانت',
    allDay: '٢٤ کاتژمێر',
    openOnly: 'تەنها کراوەکان',
    currentArea: 'ناوەندی سلێمانی',
    fromYou: 'شوێنی ئێستات',
  },
  en: {
    home: 'Home',
    community: 'Car questions',
    settings: 'Settings',
    favorites: 'Favorites',
    greeting: 'Wherever you are, help is close',
    headline: 'Keep your journey going.',
    intro:
      'Find the right tire specialist, get the help you need, and get back on the road with confidence.',
    network: 'Sulaymaniyah service network',
    help: 'Need a helping hand?',
    helpText:
      'Choose your location. Your request reaches a nearby, available fitter.',
    request: 'Request a fitter',
    browse: 'Find your fitter',
    explore: 'Explore the map',
    available: 'Available',
    offline: 'Unavailable',
    busy: 'Busy',
    saved: 'Your favorite fitters',
    savedText: 'The specialists you saved, all in one place.',
    save: 'Save fitter',
    unsave: 'Remove favorite',
    savedEmpty: 'No favorites yet',
    savedHint: 'Tap the heart on a fitter card to save it here.',
    allFitters: 'All fitters',
    filters: 'Filters',
    byDistance: 'Nearest first',
    byRating: 'Highest rated',
    area: 'All areas',
    list: 'fitters',
    noRating: 'No reviews yet',
    serviceNote: 'The right service for your journey',
    mapTitle: 'Help around the corner',
    mapText: 'Explore local workshops and mobile fitters on the map.',
    how: 'A little help. Three simple steps.',
    steps: [
      'Choose your location',
      'A fitter accepts your request',
      'Finish the job and leave a review',
    ],
    communityTitle: 'Talk it through with a specialist',
    communityText:
      'A strange noise? A tire problem? Share the details and hear from local fitters.',
    communityAction: 'Explore car questions',
    private: 'Fitter numbers stay private. Manage your request in the app.',
    appearance: 'Appearance',
    preferences: 'Make yourself at home',
    settingsIntro: 'Your language, appearance, and preferences in one place.',
    dark: 'Dark',
    light: 'Light',
    system: 'System',
    city: 'City',
    cityHint: 'Currently serving Sulaymaniyah.',
    location: 'Show distance from you',
    locationHint:
      'Location is used with your permission and is not saved on your device.',
    enabled: 'Enabled',
    disabled: 'Disabled',
    share: 'Share the app',
    copied: 'Link copied',
    install: 'Install the app',
    installHint: 'Open your browser menu and choose “Add to Home Screen”.',
    privacy: 'Privacy',
    terms: 'Terms of use',
    about: 'About NearestFitter',
    localSaved: 'Favorites are saved on this device.',
    version: 'Version 2.0 · Made for your journey',
    allDay: '24 hours',
    openOnly: 'Open now only',
    currentArea: 'Sulaymaniyah center',
    fromYou: 'Your current location',
  },
  ar: {
    home: 'الرئيسية',
    community: 'مشاكل السيارة',
    settings: 'الإعدادات',
    favorites: 'المفضلة',
    greeting: 'أينما كنت، المساعدة قريبة',
    headline: 'رحلتك مستمرة.',
    intro: 'اعثر على المختص المناسب، احصل على المساعدة، وعد إلى الطريق بثقة.',
    network: 'شبكة خدمات السليمانية',
    help: 'تحتاج إلى مساعدة؟',
    helpText: 'حدد موقعك ليصل طلبك إلى فني قريب ومتاح.',
    request: 'اطلب فنياً',
    browse: 'ابحث عن فني',
    explore: 'استكشف الخريطة',
    available: 'متاح',
    offline: 'غير متاح',
    busy: 'مشغول',
    saved: 'الفنيون المفضلون',
    savedText: 'كل المختصين الذين حفظتهم في مكان واحد.',
    save: 'حفظ في المفضلة',
    unsave: 'إزالة من المفضلة',
    savedEmpty: 'لا توجد مفضلة بعد',
    savedHint: 'اضغط القلب على بطاقة الفني لحفظها هنا.',
    allFitters: 'جميع الفنيين',
    filters: 'تصفية',
    byDistance: 'الأقرب أولاً',
    byRating: 'الأعلى تقييماً',
    area: 'جميع المناطق',
    list: 'فني',
    noRating: 'لا توجد تقييمات',
    serviceNote: 'الخدمة المناسبة لرحلتك',
    mapTitle: 'المساعدة بالقرب منك',
    mapText: 'استكشف الورش والفنيين المتنقلين على الخريطة.',
    how: 'كيف يعمل؟',
    steps: ['حدد موقعك', 'يقبل الفني طلبك', 'أكمل الخدمة وشارك تقييمك'],
    communityTitle: 'ناقش المشكلة مع المختصين',
    communityText:
      'صوت غريب؟ مشكلة في الإطار؟ شارك التفاصيل واقرأ ردود الفنيين.',
    communityAction: 'استكشف النقاشات',
    private: 'تبقى أرقام الفنيين خاصة؛ إدارة الطلب داخل التطبيق.',
    appearance: 'المظهر',
    preferences: 'إعدادات تناسبك',
    settingsIntro: 'اللغة والمظهر والتفضيلات في مكان واحد.',
    dark: 'داكن',
    light: 'فاتح',
    system: 'النظام',
    city: 'المدينة',
    cityHint: 'الخدمة متاحة حالياً في السليمانية.',
    location: 'عرض المسافة من موقعك',
    locationHint: 'نستخدم موقعك بإذنك ولا نحفظه على جهازك.',
    enabled: 'مفعّل',
    disabled: 'معطّل',
    share: 'مشاركة التطبيق',
    copied: 'تم نسخ الرابط',
    install: 'تثبيت التطبيق',
    installHint: 'اختر «إضافة إلى الشاشة الرئيسية» من قائمة المتصفح.',
    privacy: 'الخصوصية',
    terms: 'شروط الاستخدام',
    about: 'عن أقرب فني',
    localSaved: 'تُحفظ المفضلة على هذا الجهاز.',
    version: 'الإصدار ٢.٠ · من أجل رحلتك',
    allDay: '٢٤ ساعة',
    openOnly: 'المفتوح الآن فقط',
    currentArea: 'مركز السليمانية',
    fromYou: 'موقعك الحالي',
  },
};
